### ISSUE TITLE
Vulkan applications  crash on startup when the layer is loaded

### ISSUE THREAD

**Issue by Mon-Ouie** [nyorain/vil#13]
Would love to try this, but I've always had the code crash when starting up (running on X11 with proprietary NVidia drivers 550.54.14, with the layer installed in ``/usr/local``):
```
$ VIL_CREATE_WINDOW=1 VK_INSTANCE_LAYERS="VK_LAYER_live_introspection" vkcube
[src/layer.cpp:238] Trying to manually bump instance apiVersion to 1.2 instead of 1.0 provided by application
Selected GPU 0: NVIDIA GeForce GTX 1080, type: DiscreteGpu
[subprojects/swa/src/swa/wayland.c:2706] wl_display_connect: No such file or directory
[subprojects/swa/src/swa/x11.c:1555] visualid: 33, depth: 24
ERROR:             vkCreateSwapchainKHR: Driver's function pointer was NULL, returning VK_SUCCESS. Was the VK_KHR_swapchain extension enabled?
[src/window.cpp:249] assertion 'swapchain' failed: 'We likely called the stub vkCreateSwapchainKHR implementation, maybe we didn't enable the extension correctly'
zsh: segmentation fault (core dumped)  VIL_CREATE_WINDOW=1 VK_INSTANCE_LAYERS="VK_LAYER_live_introspection" vkcube
```

**Comment by nyorain** [comment]
Thanks, I can reproduce the issue. Will have a look.

**Comment by nyorain** [comment]
Fixed.
For future reference: Before https://github.com/KhronosGroup/Vulkan-Loader/pull/1049, it was possible to call CreateSwapchainKHR right inside the layer's device creation function (where we initialize the window). Since this function call now depends on loader dispatch tables only initialized after *all* CreateDevice functions have finished, this approach is not possible anymore. Instead, we now delay initialization. I added init checks to vkQueueSubmit(2) and vkAllocateMemory, only the first time such a function is called will the vil window be opened. Could add it to other functions in future.
